spring:
  datasource:
    url: jdbc:mysql://localhost:3306/service
    username: {MYSQL_NAME}
    password: {MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

JWT:
  secret-key: ${JWT_SECRET_KEY}
  expiration-time: 86400000
  header: Authorization
  prefix: Bearer

mybatis:
  config-location: classpath:/mybatis-config.xml
  mapper-locations: classpath:/mybatis/mapper/*.xml

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operations-sorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /api/v1/**