spring:
  datasource:
    url: jdbc:mysql://localhost:3307/service
    username: {MYSQL_NAME}
    password: {MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: "localhost
      port: 6379
      password: {REDIS_PASSWORD}
      timeout: {REDIS_TIMEOUT}

JWT:
  SECRET_KEY: {SECRET_KEY}
  EXPIRATION_TIME: 14400000
  header: Authorization
  prefix: Bearer

mybatis:
  config-location: classpath:/mybatis-config.xml
  mapper-locations: classpath:/mybatis/mapper/*.xml

ENCRYPT:
  ENCRYPT_SECRET_KEY: {ENCRYPT_SECRET_KEY}
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    groups-order: DESC
    operations-sorter: method
    disable-swagger-default-url: true
    display-request-duration: true
  api-docs:
    path: /api-docs
  show-actuator: true
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  paths-to-match:
    - /api/v1/**